#!/bin/sh
echo "Fullpath: $ITERATOR_FULL_PATH"
echo "Name: $ITERATOR_FILE_NAME"
echo "Name without extension: $ITERATOR_FILE_NAME_WITHOUT_EXTENSION"
echo "Current directory: $ITERATOR_CURRENT_DIR"
echo "Current relative directory: $ITERATOR_CURRENT_REL_DIR"
echo "Base directory: $ITERATOR_BASE_DIR"
echo "Target directory: $ITERATOR_TARGET_DIR"
echo "Arg 1: $1"
echo "Arg 2: $2"
echo "Arg 3: $3"
echo "-----------------------------"
